package pmel.sdig.las

import org.apache.shiro.authc.credential.PasswordService

/**
 * Generated by the Shiro plugin. This interceptor class protects all URLs
 * via access control by convention.
 */

class AdminInterceptor {
    PasswordService credentialMatcher
    boolean defaultpw = false
    //customize me
    int order = HIGHEST_PRECEDENCE+100

    boolean before() {
        def adminUser = ShiroUser.findByUsername('admin')
        if ( credentialMatcher.passwordsMatch('default', adminUser.passwordHash) ) {
            defaultpw = true
            return true;
        } else {
            // Access control by convention.
            accessControl()
        }
    }
    boolean after() {
        if ( defaultpw )
            view = 'default'
        true
    }
    void afterView() {
    }
}
